export const GET_POKEMON_SPECIES = "GET_POKEMON_SPECIES";
export const GET_POKEMON_SPECIES_SUCCESS = "GET_POKEMON_SPECIES_SUCCESS";
export const GET_POKEMON_SPECIES_FAILURE = "GET_POKEMON_SPECIES_FAILURE";
export const GET_POKEMON = "GET_POKEMON";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAILURE = "GET_POKEMON_FAILURE";
export const POKEMON_SELECTED = "POKEMON_SELECTED";